### PR TITLE
fix overflow for ie11

### PR DESCRIPTION
**Pull request by iwwwi**
# What does this PR do:

   Fixes overflow problem on IE 11 Issue #296 

before: 
https://cl.ly/3F0O1e0u092M

After:
https://cl.ly/3h0f3b0O3Q2S
# Where should the reviewer start:

    Diff in styles

### CODE REVIEW

**Comment by froskie** [comment]
What's with the difference in the snapshots since you didn't touch any code related to that?

**Comment by leandrooriente** [comment]
In IE 11 the modal title is scrolling together with the content.

The same behavior doesn't happen in Edge or Chrome for example.

**Comment by froskie** [comment]
Although I agree with @leandrooriente , I believe this fix the overflow problem _per se_. We should address the fixed header and footer in somewhere else.

**Comment by iwwwi** [comment]
@leandrooriente  IMHO at the moment users are blocked to scroll the content in general without this fix :D and the header not being there is not a blocker :D can be fixed later... but I do not have time now to check this at moment... :D we can either merge this PR as fix for this bug (being blocked to scroll) and create another issue to improve the header experience ... or decline everything until I get the time to work on this again... or someone else can extend this PR :D I am ok in general with all approaches :)

**Comment by yurist38** [comment]
Header/footer problem is not fully a scope of the current PR as I can see. Agree that ideally to fix it here as well. But since it requires more resources, I prefer to merge this PR asap and create an issue for the header/footer.

**Comment by leandrooriente** [comment]
👍 

I created a new issue to track this problem: https://github.com/Travix-International/travix-ui-kit/issues/353

**Pull request merged**
