### PR TITLE
Remove wrong attribute from svg

### PR DESCRIPTION
**Pull request by DzmitryKukharuk**
# What does this PR do:
   Spinner component has a wrong attribute "styles". This attr has been removed.

# Where should the reviewer start:

   Please see the diff

### CODE REVIEW

**Comment by asci** [comment]
why remove? Why not fix? also, could you please add a picture of the spinner (using non white background)?

**Comment by DzmitryKukharuk** [comment]
image

The spinner with my changes looks totally the same as without. It means that "styles" attr is redundant and does not impact spinner`s style.

**Comment by AlleeX** [comment]
@DzmitryKukharuk did you check not others background colors? Can you please add example with (for example)  blue background to the docs

Like this

selection_122


Thanks ;)

**Comment by DzmitryKukharuk** [comment]
Hi Alleex,
sure, I checked with diff colors.
This is an example with blue color:
image

**Pull request merged**
