### PR TITLE
fixed styles for the list component

### PR DESCRIPTION
**Pull request by MadinaShad**
# What does this PR do:

    Fixes styles for the List component:
   1.)  aligns multi-line text after icons
screenshot-1
   2.) removes icons if the prop hideBullets is true
52d38c9b0015c9843ef3dbee7cf0aabe _image 2018-02-26 at 2 02 49 pm

# How it looks now:
screen shot 2018-02-26 at 15 09 38

# Where should the reviewer start:

    Diff/acceptance link

### CODE REVIEW

**Comment by AlexDudar** [comment]
if I apply `hideBullets` to the horizontal list, it becomes vertical.. not sure if it's desired behavior 

screen shot 2018-02-26 at 3 45 22 pm

**Comment by MadinaShad** [comment]
@AlexDudar mmm, looks like we don't use the icons on horizontal list. That means we shouldn't use any props to remove them. No icons, no problem 😄

**Comment by MadinaShad** [comment]
@leandrooriente oh, will check it, thanks!

**Comment by AlexDudar** [comment]
@MadinaShad , technically icons are present, they just hidden since `li` having `display: inline-block`. I don't think that hiding icons should affect/check if list is vertical or horizontal, it's simply weird to me, but of course it's your call ;)

**Comment by yurist38** [comment]
Actually, I have used a horizontal list with the icons on Seatmap. I guess it's still there (below the header of the sidepanel).

**Comment by MadinaShad** [comment]
@AlexDudar @yurist38 icons are present ONLY for vertical list, if we need to show icons on horizontal list we have to extend our ui-kit) And that problem which Alex has mentioned before I will fix

**Comment by EduardTrutsyk** [comment]
is it possible to use different icons at the same time?
Like this:
screenshot at 11-09-22
screenshot at 11-15-35

**Comment by MadinaShad** [comment]
@EduardTrutsyk It’s a very good question. The list doesn’t have this functionality. We have to think about it later

**Comment by EduardTrutsyk** [comment]
one more question, why the prop name is `hideBullets`? 
maybe better to name it `hideIcons`? 
and on you example we have check marks :smiley:

**Comment by rbardini** [comment]
Agree with @EduardTrutsyk, I think we should have a more generic prop name for this. The [MDN docs](https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-type) call them "markers". Maybe we could have a `noMarkers` prop?

**Comment by iwwwi** [comment]
@EduardTrutsyk @rbardini can you pls create a proposal for extending this component with this options? Pls add those details in both github issues section and our JIra board :) tnx

**Pull request merged**
