### PR TITLE
Setup Now for deploying to accp

### LINKED ISSUE #229: Deploy feature branch (styleguide) to test server
# Browsers and versions affected

> All

# Description

> When you create PR would be nice to provide test (acceptance) link to make it easier and faster to test and review. Some options coming into my mind: [Heroku](https://www.heroku.com/), [Now/Zeit](https://zeit.co/now). @fahad19 mentioned [Bitbaloon](https://www.bitballoon.com/) as a good option.

# Expected results

> `npm run` script to deploy branch to the acceptance returning the link.
>

Feel free to give us your idea!

### PR DESCRIPTION
**Pull request by yurist38**
# What does this PR do:
* Fixes #229 
* Added `now` package to the dependencies list and created npm script `deploy:accp`. On the first deployment, you most probably will be asked to login/signup to `Now`. It's easy, just install it and enter your e-mail address and confirm it then. Once the script is completed you will see the link to the deployed site in the console (and it will be automatically copied to the clipboard).

# Where should the reviewer start:
* Install [Now](https://zeit.co/now)
* `git checkout setup-accp-deployment`
* `npm run deploy:accp`

### CODE REVIEW

**Comment by mAiNiNfEcTiOn** [comment]
Wonderful idea @yurist38

**Comment by mAiNiNfEcTiOn** [comment]
@yurist38 in case of the PR #235, your acceptance link has an error when pressing on the _code_ feature on any component:

screen shot 2017-11-20 at 13 57 12

**Comment by yurist38** [comment]
@mAiNiNfEcTiOn It's related to PR #236  . This accp use still old version of `react-styleguide`, code button functionality will be fixed after merging that PR.

**Comment by mAiNiNfEcTiOn** [comment]
Yeah just noticed it, thanks for your feedback @yurist38 ... let's merge it first then 😉

**Pull request merged**
